### ISSUE TITLE
一覧画面作成

### ISSUE THREAD

**Issue by tokumori24** [e225724/hello-tech-jam#2]

**Comment by Koja-uta** [comment]
一覧画面作成

作成するもの：

- 絞り込み後の店一覧を表示させる
    -   店それぞれの「全体的評価」「名前」「価格帯」「エリア」「お店の写真」を出力する
    -   横列で一気に5個表示させる
    -   絞り込みのボタンを押すと、絞り込み機能に飛ぶ(この時の絞り込み機能は一覧の上に表示されるポップアウト方式)
